import json
import uuid
from fastapi import APIRouter, Depends, Response, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from app.api.deps import get_current_user
from app.db.session import get_db
from app.models.action_item import ActionItem
from app.models.decision import Decision
from app.models.meeting_insight import MeetingInsight
from app.models.meeting_topic import MeetingTopic
from app.models.transcript import TranscriptSegment
from app.models.user import User
from app.schemas.transcript import format_seconds_to_timestamp
from app.services.meeting.meeting_service import MeetingService

router = APIRouter(prefix="/meetings", tags=["Export"])


@router.get(
    "/{meeting_id}/export/markdown",
    summary="Export meeting intelligence as Markdown file",
)
async def export_markdown(
    meeting_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    meeting = await MeetingService.get_meeting(db, meeting_id, current_user.id)

    # Fetch insight
    insight_q = await db.execute(select(MeetingInsight).where(MeetingInsight.meeting_id == meeting_id))
    insight = insight_q.scalar_one_or_none()

    # Fetch actions, decisions, topics
    actions_q = await db.execute(select(ActionItem).where(ActionItem.meeting_id == meeting_id))
    actions = list(actions_q.scalars().all())

    decisions_q = await db.execute(select(Decision).where(Decision.meeting_id == meeting_id))
    decisions = list(decisions_q.scalars().all())

    topics_q = await db.execute(select(MeetingTopic).where(MeetingTopic.meeting_id == meeting_id))
    topics = list(topics_q.scalars().all())

    # Build Markdown document
    lines = [
        f"# {meeting.title}",
        f"*Meeting Intelligence Report generated by MeetMind*",
        f"- **Date**: {meeting.created_at.strftime('%Y-%m-%d %H:%M')}",
        f"- **Duration**: {format_seconds_to_timestamp(meeting.duration_seconds)}",
        "",
        "## Executive Summary",
        insight.executive_summary if insight and insight.executive_summary else (meeting.description or "N/A"),
        "",
    ]

    if insight and insight.key_points:
        lines.append("## Key Discussion Points")
        for kp in insight.key_points:
            lines.append(f"- {kp}")
        lines.append("")

    if actions:
        lines.append("## Action Items")
        for a in actions:
            status_box = "[x]" if a.is_completed else "[ ]"
            ts = f" (at {format_seconds_to_timestamp(a.source_timestamp)})" if a.source_timestamp is not None else ""
            lines.append(f"- {status_box} **{a.task}** — *Assignee*: {a.assignee} | *Deadline*: {a.deadline}{ts}")
        lines.append("")

    if decisions:
        lines.append("## Decisions Agreed Upon")
        for d in decisions:
            ts = f" (at {format_seconds_to_timestamp(d.source_timestamp)})" if d.source_timestamp is not None else ""
            lines.append(f"- {d.decision}{ts}")
        lines.append("")

    if topics:
        lines.append("## Discussed Topics")
        for t in topics:
            lines.append(f"- **{t.topic}**: {t.summary or ''}")
        lines.append("")

    if insight and insight.detailed_summary:
        lines.append("## Detailed Summary")
        lines.append(insight.detailed_summary)
        lines.append("")

    md_content = "\n".join(lines)
    filename = f"meetmind_{meeting.title.lower().replace(' ', '_')}.md"

    return Response(
        content=md_content,
        media_type="text/markdown",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get(
    "/{meeting_id}/export/json",
    summary="Export complete meeting intelligence payload as JSON file",
)
async def export_json(
    meeting_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    meeting = await MeetingService.get_meeting(db, meeting_id, current_user.id)

    # Fetch all data
    insight_q = await db.execute(select(MeetingInsight).where(MeetingInsight.meeting_id == meeting_id))
    insight = insight_q.scalar_one_or_none()

    actions_q = await db.execute(select(ActionItem).where(ActionItem.meeting_id == meeting_id))
    actions = [
        {
            "id": str(a.id),
            "task": a.task,
            "assignee": a.assignee,
            "deadline": a.deadline,
            "source_timestamp": a.source_timestamp,
            "is_completed": a.is_completed,
        }
        for a in actions_q.scalars().all()
    ]

    decisions_q = await db.execute(select(Decision).where(Decision.meeting_id == meeting_id))
    decisions = [
        {"id": str(d.id), "decision": d.decision, "source_timestamp": d.source_timestamp}
        for d in decisions_q.scalars().all()
    ]

    topics_q = await db.execute(select(MeetingTopic).where(MeetingTopic.meeting_id == meeting_id))
    topics = [{"id": str(t.id), "topic": t.topic, "summary": t.summary} for t in topics_q.scalars().all()]

    segments_q = await db.execute(
        select(TranscriptSegment).where(TranscriptSegment.meeting_id == meeting_id).order_by(TranscriptSegment.start_time)
    )
    segments = [
        {
            "speaker": s.speaker,
            "text": s.text,
            "start_time": s.start_time,
            "end_time": s.end_time,
        }
        for s in segments_q.scalars().all()
    ]

    payload = {
        "meeting": {
            "id": str(meeting.id),
            "title": meeting.title,
            "description": meeting.description,
            "duration_seconds": meeting.duration_seconds,
            "status": meeting.status,
            "created_at": meeting.created_at.isoformat(),
        },
        "summary": {
            "executive_summary": insight.executive_summary if insight else None,
            "key_points": insight.key_points if insight else [],
            "detailed_summary": insight.detailed_summary if insight else None,
            "risks": insight.risks if insight else [],
            "questions": insight.questions if insight else [],
        },
        "action_items": actions,
        "decisions": decisions,
        "topics": topics,
        "transcript_segments": segments,
    }

    json_str = json.dumps(payload, indent=2)
    filename = f"meetmind_{meeting.title.lower().replace(' ', '_')}.json"

    return Response(
        content=json_str,
        media_type="application/json",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get(
    "/{meeting_id}/export/txt",
    summary="Export plain text transcript",
)
async def export_txt(
    meeting_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    meeting = await MeetingService.get_meeting(db, meeting_id, current_user.id)

    segments_q = await db.execute(
        select(TranscriptSegment).where(TranscriptSegment.meeting_id == meeting_id).order_by(TranscriptSegment.start_time)
    )
    segments = segments_q.scalars().all()

    lines = [
        f"MEETMIND TRANSCRIPT: {meeting.title}",
        f"Date: {meeting.created_at.strftime('%Y-%m-%d')}",
        "--------------------------------------------------",
        "",
    ]
    for s in segments:
        ts = f"[{format_seconds_to_timestamp(s.start_time)} - {format_seconds_to_timestamp(s.end_time)}]"
        lines.append(f"{ts} {s.speaker}: {s.text}")

    txt_content = "\n".join(lines)
    filename = f"transcript_{meeting.title.lower().replace(' ', '_')}.txt"

    return Response(
        content=txt_content,
        media_type="text/plain",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
